### PR TITLE
refactor card methodology validation to only valide with C

### PR DESCRIPTION
**Pull request by Caleb-Nieto**
### Feature / Bug Description
refactor card methodology validation to only valide with C
### Solution
refactor card methodology validation to only valide with C

### Notes
no notes needed

### Tickets
[WMA-121](https://cdentalcaregroup.atlassian.net/browse/WMA-121)

### Screenshots / Screencasts
When a card with comportamiento methodology type is created
Captura de pantalla 2024-07-02 133425
When a card without comportamiento methodology type is created
Captura de pantalla 2024-07-02 133502

[WMA-121]: https://cdentalcaregroup.atlassian.net/browse/WMA-121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by imadiaz — COMMENTED** [review]
if in the request the "cardType" value i send null what happen?

**Comment by Caleb-Nieto** [comment]
image

**Comment by Caleb-Nieto** [comment]
I ll change it if you want

**Comment by imadiaz** [comment]
> I ll change it if you want



> I ll change it if you want

Yes you need to remove that validation, i can send null value for that and it should work

**Comment by Caleb-Nieto** [comment]
image

**Review by imadiaz — APPROVED** [review]

**Pull request merged**
